version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_EMAIL: 'admin@example.com'
      DJANGO_SUPERUSER_PASSWORD: 'securepassword'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.sh
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: 'booksdb'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'Password13!'
      MYSQL_ROOT_PASSWORD: 'Password13!'
    ports:
      - "3306:3306"